[package]
name = "elp-omega-rust"
version = "1.0.0"
edition = "2021"

[dependencies]
hmac = "0.12.1"
sha2 = "0.10.8"
base64 = "0.21.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"
uuid = { version = "1.4.1", features = ["v4"] }